from gym.envs.algorithmic.copy_ import CopyEnv
from gym.envs.algorithmic.copy_c import CopyEnv2
from gym.envs.algorithmic.repeat_copy import RepeatCopyEnv
from gym.envs.algorithmic.duplicated_input import DuplicatedInputEnv
from gym.envs.algorithmic.duplicated_input_c import DuplicatedInputEnv6
from gym.envs.algorithmic.reverse import ReverseEnv
from gym.envs.algorithmic.reversed_addition import ReversedAdditionEnv
from gym.envs.algorithmic.reversed_addition_c import ReversedAdditionEnv6
from gym.envs.algorithmic.single_multiplication import SingleMultiplicationEnv
from gym.envs.algorithmic.single_multiplication_c import SingleMultiplicationEnv2
